# --- Build Stage ---
FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# The db folder is here during the build
RUN npm run build

# --- Runtime Stage ---
FROM node:20-slim
WORKDIR /app

# Copy the build artifacts
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

#Copy the db folder so the seed script can find it
COPY --from=builder /app/db ./db 

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "build"]