services:
  db:
    image: postgres:16
    container_name: WordSense-db-prod
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dictionary_game
    # --- ADD THIS SECTION ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d dictionary_game"]
      interval: 5s
      timeout: 5s
      retries: 5
    # -------------------------
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql


  sveltekit:
    build: .
    container_name: WordSense-web
    depends_on:
      db:
        condition: service_healthy # Now this will work!
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_SSL: "false" 
      DATABASE_URL: postgres://devuser:devpassword@db:5432/dictionary_game
      #ORIGIN: http://127.0.0.1:3000

    command: node build

volumes:
  postgres_data_prod: